#!/usr/bin/groovy
@Library('github.com/fabric8io/fabric8-pipeline-library@master')
def dummy
mavenNode {
    container(name: 'maven') {
        sh 'rm -rf /root/.mvnrepo/io/fabric8/funktion/connector/'
    }
}
